[package]
name = "iris"
version = "0.1.0"
edition = "2021"
default-run = "iris"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "iris"
path = "src/main.rs"

[[bin]]
name = "version"
path = "scripts/version.rs"

[[bin]]
name = "name"
path = "scripts/name.rs"

[dependencies]
serenity = { git = "https://github.com/vars1ty/serenity", branch = "current" }
